"""cpuless_promote — promote SIMANTW's cleanest leaf tier to CPUless (M4 slice).

The CPU-detachment stage of the DOS_RE 2.0 adoption
(win16_re/dos_re/docs/dos_re_2.0.md §1 stage 2): for every liftable LEAF
function that has NO authoritative hand-recovered implementation, run dos_re's
``cpuless_promote`` — the strict first-subset gate + emitter — to generate a
pure-Python recovered body (``simant/native/cpuless/func_CCCC_IIII.py``,
computing over ``(mem[, plat], *regs)`` with no CPU carrier) plus a CPU-ABI
adapter that restores the historical machine ABI around it.

THE MANUAL SPLIT ([[manual-recovery-is-authoritative]]).  Where a verified
manual CPUless implementation already exists in ``simant/recovered/``, IT is
authoritative and the M2b adapter generator (scripts/adaptgen.py) wraps it —
CPUless promotion must NEVER generate a parallel body for such a function.  So
this tool promotes ONLY ``leaf ∩ ¬manual``: it reads the promotion census
(artifacts/cpuless_census.json — scripts/../cpuless_census over the recovery
IR) for the leaf tier and the recovered map (simant/facts/recovered_map.json)
for the manual corpus, and restricts the promoter's ``--entries`` to their
difference.  The two toolchains produce ONE implementation per function.

THE GRAPH SEAM.  A generated adapter is a byte-for-byte drop-in for the literal
lift it replaces — same ``(cpu, bb=0)`` signature, same historical RET, same
``owns_time`` virtual-time accounting — so it installs through the identical
``dos_re.lift.install`` machinery (LINKS late-binding + replacement_hooks).
The routed graph is materialized beside the literal graph as
``simant/lifted/graph_cpuless/``: the literal corpus is copied, each promoted
leaf's symbolically-named module is DELETED and its adapter dropped in, and the
graph manifest entry is remapped to the adapter's ``lifted_CCCC_IIII`` stem
(the ``dos_re.lift.naming`` seam every linked caller resolves through).  One
graph, one implementation per entry.

Everything written here is DISPOSABLE autogenerated output (gitignored, like
simant/lifted/graph): delete it and this script reproduces it from the IR +
census + facts.  Runs AFTER liftemit/liftlink (it builds FROM their linked
corpus); never hand-edit a generated body/adapter — fix the emitter or facts
and regenerate.

    python scripts/cpuless_promote.py            # generate + route + lint
    python scripts/cpuless_promote.py --dry-run  # census only, no files
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

import simant._env  # noqa: E402,F401
import win16  # noqa: E402,F401  (puts the nested dos_re on sys.path)

sys.path.insert(0, str(REPO_ROOT / "scripts"))
from liftemit import load_dosre_tool  # noqa: E402

DEFAULT_IR = REPO_ROOT / "artifacts" / "recovery_ir.json"
DEFAULT_CENSUS = REPO_ROOT / "artifacts" / "cpuless_census.json"
DEFAULT_MAP = REPO_ROOT / "simant" / "facts" / "recovered_map.json"
DEFAULT_FROM_DIR = REPO_ROOT / "simant" / "lifted" / "graph"
DEFAULT_GRAPH_DIR = REPO_ROOT / "simant" / "lifted" / "graph_cpuless"
DEFAULT_REC_DIR = REPO_ROOT / "simant" / "native" / "cpuless"
DEFAULT_BOUNDARY = REPO_ROOT / "artifacts" / "boundary_heads_para.txt"
DEFAULT_CENSUS_OUT = REPO_ROOT / "artifacts" / "cpuless_promote_census.json"
DEFAULT_MANIFEST = REPO_ROOT / "artifacts" / "vmless_boot" / "manifest.json"
DEFAULT_PLAT_FARCALLS = REPO_ROOT / "artifacts" / "plat_farcalls.json"
IMPORT_BASE = "simant.native.cpuless"


def para_of_seg(ir: dict) -> dict[int, str]:
    """NE segment -> its paragraph-base (the CS the IR keys that segment by)."""
    out: dict[int, str] = {}
    for entry, rec in ir["functions"].items():
        out.setdefault(rec["ne_seg"], entry.split(":")[0])
    return out


def manual_para_keys(map_doc: dict, seg_base: dict[int, str]) -> set[str]:
    """The hand-recovered corpus as paragraph-base CS:IP keys — the entries
    CPUless promotion must NOT generate a parallel body for (adaptgen owns
    them)."""
    out: set[str] = set()
    for f in map_doc["functions"]:
        k = f.get("key")
        if not k:
            continue
        seg_s, off = k.split(":")
        base = seg_base.get(int(seg_s))
        if base:
            out.add(f"{base}:{off}".upper())
    return out


def promote_entries(census: dict, manual: set[str],
                    tiers: tuple[str, ...] = ("leaf",)) -> list[str]:
    """(⋃ tiers) ∩ ¬manual — the mechanical-promotion candidates.

    The leaf slice promotes ``leaf ∩ ¬manual``; the calls-only widening adds
    the ``calls-only`` tier, which the dos_re promoter composes BOTTOM-UP over
    the near/far call DAG (its fixpoint promotes a caller only once every
    direct callee already has a CPUless contract).  The manual corpus is always
    excluded — adaptgen owns those bodies ([[manual-recovery-is-authoritative]])
    and they stay literal lifts in graph_cpuless, so a candidate that calls one
    naturally refuses ``call-abi-composition`` (an honest frontier item, not a
    parallel body)."""
    cand: set[str] = set()
    for t in tiers:
        cand |= {k.upper() for k in census["tiers"].get(t, [])}
    return sorted(cand - manual)


def build_plat_farcalls(manifest_path: Path, out_path: Path) -> tuple[int, int, int]:
    """Derive the PLATFORM far-call contracts for the CPUless emitter from the
    win16 import-thunk table.

    SimAnt reaches every KERNEL/USER/GDI/... API through a static
    ``call far THUNK_SEG:slot`` into the import thunk segment (the
    ``manifest.api_slots`` table).  dos_re's plat.farcall composition needs, per
    slot, the pascal callee-cleanup ``argbytes`` -- which is exactly the sum of
    the API's declared pascal argument sizes, the same number the win16 API
    dispatch pops in its ``ret_far`` (win16/api/core.py).  So the contract is a
    win16 fact, read straight off the api registry: NOTHING game-specific about
    SimAnt is encoded here, and dos_re stays boundary-segment-agnostic (the
    THUNK_SEG and the per-slot argbytes are handed in as data).

    A raw (-register) API owns its own return contract (arg_sizes is None) and a
    slot with no implemented entry is a gap: neither gets a contract, so a
    far-call to it REFUSES ``platform-farcall-contract-unknown`` -- an honest
    frontier item, never a guessed arg count.  Returns (thunk_seg, n_contracts,
    n_skipped)."""
    from win16.api.surface import build_registry
    from win16.app import WINFLAGS_NO_FPU

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    thunk_seg = int(manifest["thunk_seg"])
    reg = build_registry(winflags=WINFLAGS_NO_FPU)
    contracts: dict[str, dict] = {}
    skipped = 0
    for key, off in manifest["api_slots"].items():
        mod, ordn = key.rsplit(".", 1)
        entry = reg.entries.get((mod.upper(), int(ordn)))
        if entry is None or entry.arg_sizes is None:
            skipped += 1            # a gap or a raw API: no derivable argbytes
            continue
        contracts[f"{thunk_seg:04X}:{int(off):04X}"] = {
            "argbytes": sum(entry.arg_sizes),
            "cost": 1,              # one VM step per API dispatch (not owns_time)
            "name": f"{mod.upper()}.{ordn}",
        }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps({
        "_notice": "GENERATED by scripts/cpuless_promote.py from the win16 "
                   "import-thunk table (manifest.api_slots) + the api "
                   "registry's declared pascal arg sizes. Disposable; "
                   "regenerate, do not hand-edit.",
        "thunk_seg": f"{thunk_seg:04X}",
        "contracts": contracts,
    }, indent=1), encoding="utf-8")
    return thunk_seg, len(contracts), skipped


def route_graph(from_dir: Path, graph_dir: Path, adapter_dir: Path,
                promoted: list[str]) -> tuple[int, list[str]]:
    """Materialize the CPUless-routed graph: copy the literal corpus, then for
    every promoted leaf swap its literal module for the generated adapter and
    remap the manifest stem to the adapter's ``lifted_CCCC_IIII`` name.

    Returns (adapters routed, missing-adapter keys)."""
    from dos_re.lift.naming import GraphNaming

    if not (from_dir / "graph_manifest.json").is_file():
        raise SystemExit(f"cpuless_promote: no graph manifest in {from_dir} — "
                         f"run scripts/liftemit.py + scripts/liftlink.py first")
    graph_dir.mkdir(parents=True, exist_ok=True)
    for old in graph_dir.glob("*.py"):
        old.unlink()
    for src in sorted(from_dir.glob("*.py")):
        (graph_dir / src.name).write_bytes(src.read_bytes())
    for extra in ("graph_manifest.json", "boundary_policy.json"):
        if (from_dir / extra).is_file():
            (graph_dir / extra).write_bytes((from_dir / extra).read_bytes())

    naming = GraphNaming.load(graph_dir)
    mapping = dict(naming.mapping)
    routed = 0
    missing: list[str] = []
    for key in promoted:
        cs, ip = key.split(":")
        adapter_stem = f"lifted_{cs.lower()}_{ip.lower()}"
        adapter_src = adapter_dir / f"{adapter_stem}.py"
        if not adapter_src.is_file():
            missing.append(key)
            continue
        old_stem = mapping.get(key)
        if old_stem and old_stem != adapter_stem:
            old_path = graph_dir / f"{old_stem}.py"
            if old_path.is_file():
                old_path.unlink()
        (graph_dir / f"{adapter_stem}.py").write_bytes(adapter_src.read_bytes())
        mapping[key] = adapter_stem
        routed += 1
    GraphNaming(mapping).save(graph_dir)
    return routed, missing


def run_lint(rec_dir: Path) -> int:
    """CPUless recovered-purity wall: the promoted bodies import nothing but
    sibling recovered modules (no CPU carrier at any level)."""
    lint = load_dosre_tool("lint_cpuless")
    return lint.main([
        "--repo-root", str(REPO_ROOT),
        "--recovered-root", str(rec_dir.relative_to(REPO_ROOT).as_posix()),
        "--recovered-prefix", IMPORT_BASE,
        "--forbidden-module", "dos_re.cpu",
        "--forbidden-module", "dos_re.cpu386",
        "--forbidden-module", "simant.lifted",
        "--local-prefix", "dos_re", "--local-prefix", "simant",
    ])


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ir", default=str(DEFAULT_IR))
    ap.add_argument("--census", default=str(DEFAULT_CENSUS))
    ap.add_argument("--map", default=str(DEFAULT_MAP))
    ap.add_argument("--from-dir", default=str(DEFAULT_FROM_DIR),
                    help="the emitted+linked literal graph the routed flavor "
                         "is built FROM (liftemit/liftlink output)")
    ap.add_argument("--graph-dir", default=str(DEFAULT_GRAPH_DIR),
                    help="where the CPUless-routed graph is materialized")
    ap.add_argument("--recovered-dir", default=str(DEFAULT_REC_DIR),
                    help="the recovered-body package (import base "
                         f"{IMPORT_BASE})")
    ap.add_argument("--boundary-heads", default=str(DEFAULT_BOUNDARY),
                    help="@FILE of boundary-head CS:IP (paragraph) addresses "
                         "whose functions must not promote")
    ap.add_argument("--census-out", default=str(DEFAULT_CENSUS_OUT))
    ap.add_argument("--manifest", default=str(DEFAULT_MANIFEST),
                    help="the vmless boot manifest (api_slots + thunk_seg) the "
                         "platform far-call contracts are derived from")
    ap.add_argument("--plat-farcalls-out", default=str(DEFAULT_PLAT_FARCALLS),
                    help="where the derived platform far-call contracts are "
                         "written (fed to the dos_re promoter)")
    ap.add_argument("--no-plat-farcalls", action="store_true",
                    help="disable platform far-call composition (reproduce the "
                         "pre-plat.farcall calls-only slice)")
    ap.add_argument("--tiers", default="leaf,calls-only",
                    help="comma-separated census tiers to feed the promoter "
                         "(default: leaf,calls-only — the calls-only widening; "
                         "'leaf' alone reproduces the leaf slice). The promoter "
                         "composes bottom-up, so extra tiers only widen the "
                         "reachable set, never weaken the gate.")
    ap.add_argument("--dry-run", action="store_true",
                    help="run the promotion census only; write no files")
    args = ap.parse_args(argv)

    ir = json.loads(Path(args.ir).read_text(encoding="utf-8"))
    census = json.loads(Path(args.census).read_text(encoding="utf-8"))
    map_doc = json.loads(Path(args.map).read_text(encoding="utf-8"))

    tiers = tuple(t.strip() for t in args.tiers.split(",") if t.strip())
    seg_base = para_of_seg(ir)
    manual = manual_para_keys(map_doc, seg_base)
    entries = promote_entries(census, manual, tiers)
    cand_all: set[str] = set()
    for t in tiers:
        cand_all |= {k.upper() for k in census["tiers"].get(t, [])}
    tier_sizes = ", ".join(f"{t}={len(census['tiers'].get(t, []))}"
                           for t in tiers)
    print(f"tiers [{tier_sizes}]; manual-recovered (adaptgen owns): "
          f"{len(manual & cand_all)} ∩manual; CPUless-promotion candidates "
          f"(⋃tiers ∩ ¬manual): {len(entries)}")

    rec_dir = Path(args.recovered_dir)
    graph_dir = Path(args.graph_dir)
    adapter_dir = graph_dir / "_adapters"        # staging for lifted_* adapters

    promote = load_dosre_tool("cpuless_promote")
    promote_argv = [
        "--ir", args.ir,
        "--recovered-dir", str(rec_dir),
        "--adapter-dir", str(adapter_dir),
        "--import-base", IMPORT_BASE,
        "--exclude", f"@{args.boundary_heads}",
        "--entries", ",".join(entries),
        "--census-out", args.census_out,
    ]
    # PLATFORM far-call composition (plat.farcall): a `call far THUNK_SEG:slot`
    # into the win16 import-thunk table becomes a platform effect, not a refusal
    # -- the gateway to the calls-only sim tier (nearly every non-trivial sim
    # function reaches an API this way).  The THUNK_SEG + per-slot argbytes are
    # a win16 fact (derived from the api registry), handed to the emitter as
    # data; dos_re stays boundary-segment-agnostic.
    if not args.no_plat_farcalls:
        thunk_seg, n_contracts, n_skipped = build_plat_farcalls(
            Path(args.manifest), Path(args.plat_farcalls_out))
        print(f"platform far-call contracts: {n_contracts} thunk slot(s) "
              f"(seg {thunk_seg:04X}); {n_skipped} skipped (raw API / gap -- "
              f"no derivable argbytes)")
        promote_argv += [
            "--plat-far-segs", f"{thunk_seg:04X}",
            "--plat-farcalls", f"@{args.plat_farcalls_out}",
        ]
    if args.dry_run:
        print("\n=== promotion census (dry run) ===")
        return promote.main(promote_argv)

    # Clean regen: the recovered package and the adapter staging are disposable.
    if rec_dir.exists():
        shutil.rmtree(rec_dir)
    rec_dir.mkdir(parents=True, exist_ok=True)
    adapter_dir.mkdir(parents=True, exist_ok=True)

    print("\n=== promote (emit recovered bodies + CPU-ABI adapters) ===")
    rc = promote.main(promote_argv + ["--apply"])
    if rc != 0:
        return rc
    # Package marker so the adapters' `from simant.native.cpuless.func_... import`
    # resolves.  Pure (no imports) — the recovered-purity wall covers it.
    (rec_dir / "__init__.py").write_text(
        '"""AUTOGENERATED CPUless recovered corpus (scripts/cpuless_promote.py)'
        " -- disposable; regenerate, do not hand-edit.\"\"\"\n",
        encoding="utf-8", newline="\n")

    promoted = json.loads(
        Path(args.census_out).read_text(encoding="utf-8"))["promotable"]
    print("\n=== route the CPUless-routed graph "
          f"({graph_dir.relative_to(REPO_ROOT).as_posix()}) ===")
    routed, missing = route_graph(Path(args.from_dir), graph_dir, adapter_dir,
                                  promoted)
    shutil.rmtree(adapter_dir)                    # staging consumed
    if missing:
        raise SystemExit(f"cpuless_promote: {len(missing)} promoted leaf/leaves "
                         f"had no emitted adapter: {missing[:8]}")
    print(f"routed {routed} CPUless adapter(s) into {graph_dir.name}; the rest "
          f"stay literal lifts")

    print("\n=== CPUless recovered-purity wall (lint_cpuless) ===")
    rc = run_lint(rec_dir)
    if rc != 0:
        print("CPUless wall: FAIL")
        return rc
    print(f"\nCPUless slice complete: {len(promoted)} leaf function(s) promoted "
          f"to pure-Python recovered bodies + CPU-ABI adapters; wall holds.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
