"""cpuless_promote — promote SIMANTW's cleanest leaf tier to CPUless (M4 slice).

The CPU-detachment stage of the DOS_RE 2.0 adoption
(win16_re/dos_re/docs/dos_re_2.0.md §1 stage 2): for every liftable LEAF
function that has NO authoritative hand-recovered implementation, run dos_re's
``cpuless_promote`` — the strict first-subset gate + emitter — to generate a
pure-Python recovered body (``simant/native/cpuless/func_CCCC_IIII.py``,
computing over ``(mem[, plat], *regs)`` with no CPU carrier) plus a CPU-ABI
adapter that restores the historical machine ABI around it.

THE MANUAL SPLIT ([[manual-recovery-is-authoritative]]).  Where a verified
manual CPUless implementation already exists in ``simant/recovered/``, IT is
authoritative and the M2b adapter generator (scripts/adaptgen.py) wraps it —
CPUless promotion must NEVER generate a parallel body for such a function.  So
this tool promotes ONLY ``leaf ∩ ¬manual``: it reads the promotion census
(artifacts/cpuless_census.json — scripts/../cpuless_census over the recovery
IR) for the leaf tier and the recovered map (simant/facts/recovered_map.json)
for the manual corpus, and restricts the promoter's ``--entries`` to their
difference.  The two toolchains produce ONE implementation per function.

THE GRAPH SEAM.  A generated adapter is a byte-for-byte drop-in for the literal
lift it replaces — same ``(cpu, bb=0)`` signature, same historical RET, same
``owns_time`` virtual-time accounting — so it installs through the identical
``dos_re.lift.install`` machinery (LINKS late-binding + replacement_hooks).
The routed graph is materialized beside the literal graph as
``simant/lifted/graph_cpuless/``: the literal corpus is copied, each promoted
leaf's symbolically-named module is DELETED and its adapter dropped in, and the
graph manifest entry is remapped to the adapter's ``lifted_CCCC_IIII`` stem
(the ``dos_re.lift.naming`` seam every linked caller resolves through).  One
graph, one implementation per entry.

Everything written here is DISPOSABLE autogenerated output (gitignored, like
simant/lifted/graph): delete it and this script reproduces it from the IR +
census + facts.  Runs AFTER liftemit/liftlink (it builds FROM their linked
corpus); never hand-edit a generated body/adapter — fix the emitter or facts
and regenerate.

    python scripts/cpuless_promote.py            # generate + route + lint
    python scripts/cpuless_promote.py --dry-run  # census only, no files
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

import simant._env  # noqa: E402,F401
import win16  # noqa: E402,F401  (puts the nested dos_re on sys.path)

sys.path.insert(0, str(REPO_ROOT / "scripts"))
from liftemit import load_dosre_tool  # noqa: E402

DEFAULT_IR = REPO_ROOT / "artifacts" / "recovery_ir.json"
DEFAULT_CENSUS = REPO_ROOT / "artifacts" / "cpuless_census.json"
DEFAULT_MAP = REPO_ROOT / "simant" / "facts" / "recovered_map.json"
DEFAULT_FROM_DIR = REPO_ROOT / "simant" / "lifted" / "graph"
DEFAULT_GRAPH_DIR = REPO_ROOT / "simant" / "lifted" / "graph_cpuless"
DEFAULT_REC_DIR = REPO_ROOT / "simant" / "native" / "cpuless"
DEFAULT_BOUNDARY = REPO_ROOT / "artifacts" / "boundary_heads_para.txt"
DEFAULT_CENSUS_OUT = REPO_ROOT / "artifacts" / "cpuless_promote_census.json"
DEFAULT_MANIFEST = REPO_ROOT / "artifacts" / "vmless_boot" / "manifest.json"
DEFAULT_PLAT_FARCALLS = REPO_ROOT / "artifacts" / "plat_farcalls.json"
DEFAULT_DYN_EVIDENCE = REPO_ROOT / "artifacts" / "indirect_sites.json"
DEFAULT_OVERRIDES = REPO_ROOT / "artifacts" / "overrides.json"
IMPORT_BASE = "simant.native.cpuless"

#: THE SKIN CONFIGURATION (task #53, the owner's directive: "the lifted cpuless
#: code works as a SKELETON and our manually lifted code is SKIN that will be
#: added on that skeleton").  ONE override corpus, TWO graphs:
#:
#:   production  simant/native/cpuless      generated-only (+ time-exact
#:               simant/lifted/graph_cpuless  overrides) -- the PINNED,
#:                                            instruction-count-keyed
#:                                            byte-exact gate runs on this and
#:                                            it must never move.
#:   skin        simant/native/cpuless_skin  EVERY routable hand-recovered body
#:               simant/lifted/graph_cpuless_skin  composed as a DIRECT CPUless
#:                                            override, island cost included --
#:                                            what scripts/play_cpuless.py runs.
#:
#: They are separate DIRECTORIES because a generated body and its override share
#: the ``func_<para>_<ip>`` module name: writing an island override into the
#: production corpus would silently CLOBBER the instruction-exact twin the gate
#: depends on (cont.248 found this while wiring).  Two dirs make the split
#: structural instead of a flag people must remember.
SKIN_REC_DIR = REPO_ROOT / "simant" / "native" / "cpuless_skin"
SKIN_GRAPH_DIR = REPO_ROOT / "simant" / "lifted" / "graph_cpuless_skin"
SKIN_CENSUS_OUT = REPO_ROOT / "artifacts" / "cpuless_promote_census_skin.json"


def import_base_of(rec_dir: Path) -> str:
    """The python import base for a recovered-corpus DIRECTORY (the emitted
    bodies' package).  Derived, not hardcoded, so a second corpus flavour can
    live beside the pinned one."""
    return ".".join(rec_dir.resolve().relative_to(REPO_ROOT).parts)


def para_of_seg(ir: dict) -> dict[int, str]:
    """NE segment -> its paragraph-base (the CS the IR keys that segment by)."""
    out: dict[int, str] = {}
    for entry, rec in ir["functions"].items():
        out.setdefault(rec["ne_seg"], entry.split(":")[0])
    return out


def manual_para_keys(map_doc: dict, seg_base: dict[int, str]) -> set[str]:
    """The hand-recovered corpus as paragraph-base CS:IP keys — the entries
    CPUless promotion must NOT generate a parallel body for (adaptgen owns
    them)."""
    out: set[str] = set()
    for f in map_doc["functions"]:
        k = f.get("key")
        if not k:
            continue
        seg_s, off = k.split(":")
        base = seg_base.get(int(seg_s))
        if base:
            out.add(f"{base}:{off}".upper())
    return out


def promote_entries(census: dict, manual: set[str],
                    tiers: tuple[str, ...] = ("leaf",)) -> list[str]:
    """(⋃ tiers) ∩ ¬manual — the mechanical-promotion candidates.

    The leaf slice promotes ``leaf ∩ ¬manual``; the calls-only widening adds
    the ``calls-only`` tier, which the dos_re promoter composes BOTTOM-UP over
    the near/far call DAG (its fixpoint promotes a caller only once every
    direct callee already has a CPUless contract).  The manual corpus is always
    excluded — adaptgen owns those bodies ([[manual-recovery-is-authoritative]])
    and they stay literal lifts in graph_cpuless, so a candidate that calls one
    naturally refuses ``call-abi-composition`` (an honest frontier item, not a
    parallel body)."""
    cand: set[str] = set()
    for t in tiers:
        cand |= {k.upper() for k in census["tiers"].get(t, [])}
    return sorted(cand - manual)


def build_plat_farcalls(manifest_path: Path, out_path: Path) -> tuple[int, int, int]:
    """Derive the PLATFORM far-call contracts for the CPUless emitter from the
    win16 import-thunk table.

    SimAnt reaches every KERNEL/USER/GDI/... API through a static
    ``call far THUNK_SEG:slot`` into the import thunk segment (the
    ``manifest.api_slots`` table).  dos_re's plat.farcall composition needs, per
    slot, the pascal callee-cleanup ``argbytes`` -- which is exactly the sum of
    the API's declared pascal argument sizes, the same number the win16 API
    dispatch pops in its ``ret_far`` (win16/api/core.py).  So the contract is a
    win16 fact, read straight off the api registry: NOTHING game-specific about
    SimAnt is encoded here, and dos_re stays boundary-segment-agnostic (the
    THUNK_SEG and the per-slot argbytes are handed in as data).

    A raw (-register) API owns its own return contract (arg_sizes is None) and a
    slot with no implemented entry is a gap: neither gets a contract, so a
    far-call to it REFUSES ``platform-farcall-contract-unknown`` -- an honest
    frontier item, never a guessed arg count.  Returns (thunk_seg, n_contracts,
    n_skipped)."""
    from win16.api.surface import build_registry
    from win16.app import WINFLAGS_NO_FPU

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    thunk_seg = int(manifest["thunk_seg"])
    reg = build_registry(winflags=WINFLAGS_NO_FPU)
    contracts: dict[str, dict] = {}
    skipped = 0
    for key, off in manifest["api_slots"].items():
        mod, ordn = key.rsplit(".", 1)
        entry = reg.entries.get((mod.upper(), int(ordn)))
        if entry is None or entry.arg_sizes is None:
            skipped += 1            # a gap or a raw API: no derivable argbytes
            continue
        contracts[f"{thunk_seg:04X}:{int(off):04X}"] = {
            "argbytes": sum(entry.arg_sizes),
            "cost": 1,              # one VM step per API dispatch (not owns_time)
            "name": f"{mod.upper()}.{ordn}",
        }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps({
        "_notice": "GENERATED by scripts/cpuless_promote.py from the win16 "
                   "import-thunk table (manifest.api_slots) + the api "
                   "registry's declared pascal arg sizes. Disposable; "
                   "regenerate, do not hand-edit.",
        "thunk_seg": f"{thunk_seg:04X}",
        "contracts": contracts,
    }, indent=1), encoding="utf-8")
    return thunk_seg, len(contracts), skipped


def route_graph(from_dir: Path, graph_dir: Path, adapter_dir: Path,
                promoted: list[str], overrides: list[str] | None = None
                ) -> tuple[int, list[str]]:
    """Materialize the CPUless-routed graph: copy the literal corpus, then for
    every promoted leaf (and every authoritative OVERRIDE) swap its literal
    module for the generated adapter and remap the manifest stem to the
    adapter's ``lifted_CCCC_IIII`` name.  An override adapter is the identity-
    preserving bridge to the hand-recovered body (the unified override-graph
    seam); it occupies the SAME lifted slot a generated twin would.

    Returns (adapters routed, missing-adapter keys)."""
    from dos_re.lift.naming import GraphNaming

    if not (from_dir / "graph_manifest.json").is_file():
        raise SystemExit(f"cpuless_promote: no graph manifest in {from_dir} — "
                         f"run scripts/liftemit.py + scripts/liftlink.py first")
    graph_dir.mkdir(parents=True, exist_ok=True)
    for old in graph_dir.glob("*.py"):
        old.unlink()
    for src in sorted(from_dir.glob("*.py")):
        (graph_dir / src.name).write_bytes(src.read_bytes())
    for extra in ("graph_manifest.json", "boundary_policy.json"):
        if (from_dir / extra).is_file():
            (graph_dir / extra).write_bytes((from_dir / extra).read_bytes())

    naming = GraphNaming.load(graph_dir)
    mapping = dict(naming.mapping)
    routed = 0
    missing: list[str] = []
    for key in list(promoted) + list(overrides or []):
        cs, ip = key.split(":")
        adapter_stem = f"lifted_{cs.lower()}_{ip.lower()}"
        adapter_src = adapter_dir / f"{adapter_stem}.py"
        if not adapter_src.is_file():
            missing.append(key)
            continue
        old_stem = mapping.get(key)
        if old_stem and old_stem != adapter_stem:
            old_path = graph_dir / f"{old_stem}.py"
            if old_path.is_file():
                old_path.unlink()
        (graph_dir / f"{adapter_stem}.py").write_bytes(adapter_src.read_bytes())
        mapping[key] = adapter_stem
        routed += 1
    GraphNaming(mapping).save(graph_dir)
    return routed, missing


def run_lint(rec_dir: Path, import_base: str = IMPORT_BASE) -> int:
    """CPUless recovered-purity wall: the promoted bodies (and the carrier-free
    override bodies) import nothing but sibling recovered modules and the
    authoritative recovered corpus (``simant.recovered`` / ``simant.bridge``,
    both proven VM-free) -- no CPU carrier at any level.

    The override seam widens the wall to the WHOLE recovered corpus: an override
    body binds a bridge view (``simant.bridge.dgroup_view.SelectorBackend``) and
    calls a hand-recovered function (``simant.recovered.*``), so those two
    packages are scanned for purity and admitted as sibling-recovered prefixes.
    They reach neither ``dos_re.cpu`` nor ``simant.lifted`` (checked here), so
    the standalone runtime still never touches a CPU.

    The ``--root`` half is the RUNNER closure (cont.251): every module
    ``scripts/play_cpuless.py`` can import — its own lazy imports followed,
    then module-level edges transitively — must be CPU-free too.  The runtime
    import guard the runner arms only fires on an executed import; this is the
    static proof for the paths a given run does not take."""
    lint = load_dosre_tool("lint_cpuless")
    return lint.main([
        "--repo-root", str(REPO_ROOT),
        "--root", "scripts/play_cpuless.py",
        "--recovered-root", str(rec_dir.relative_to(REPO_ROOT).as_posix()),
        "--recovered-root", "simant/recovered",
        "--recovered-root", "simant/bridge",
        "--recovered-prefix", import_base,
        "--recovered-prefix", "simant.recovered",
        "--recovered-prefix", "simant.bridge",
        "--forbidden-module", "dos_re.cpu",
        "--forbidden-module", "dos_re.cpu386",
        "--forbidden-module", "dos_re.lift.install",
        "--forbidden-module", "dos_re.lift.runtime",
        "--forbidden-module", "dos_re.runtime",
        "--forbidden-module", "simant.lifted",
        "--forbidden-module", "simant.hooks",
        "--forbidden-module", "win16.loader",
        "--forbidden-module", "win16.bootimage",
        "--local-prefix", "dos_re", "--local-prefix", "simant",
        "--local-prefix", "win16",
        "--package-dir", "win16=win16_re/win16",
        "--package-dir", "dos_re=win16_re/dos_re/dos_re",
    ])


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ir", default=str(DEFAULT_IR))
    ap.add_argument("--census", default=str(DEFAULT_CENSUS))
    ap.add_argument("--map", default=str(DEFAULT_MAP))
    ap.add_argument("--from-dir", default=str(DEFAULT_FROM_DIR),
                    help="the emitted+linked literal graph the routed flavor "
                         "is built FROM (liftemit/liftlink output)")
    ap.add_argument("--graph-dir", default=str(DEFAULT_GRAPH_DIR),
                    help="where the CPUless-routed graph is materialized")
    ap.add_argument("--recovered-dir", default=str(DEFAULT_REC_DIR),
                    help="the recovered-body package (import base "
                         f"{IMPORT_BASE})")
    ap.add_argument("--boundary-heads", default=str(DEFAULT_BOUNDARY),
                    help="@FILE of boundary-head CS:IP (paragraph) addresses "
                         "whose functions must not promote")
    ap.add_argument("--census-out", default=str(DEFAULT_CENSUS_OUT))
    ap.add_argument("--manifest", default=str(DEFAULT_MANIFEST),
                    help="the vmless boot manifest (api_slots + thunk_seg) the "
                         "platform far-call contracts are derived from")
    ap.add_argument("--plat-farcalls-out", default=str(DEFAULT_PLAT_FARCALLS),
                    help="where the derived platform far-call contracts are "
                         "written (fed to the dos_re promoter)")
    ap.add_argument("--dyn-evidence", default=str(DEFAULT_DYN_EVIDENCE),
                    help="indirect_sites.json (per-site observed dynamic-target "
                         "evidence from scripts/entry_probe.py): a function with "
                         "a dynamic transfer promotes only when every OBSERVED "
                         "target of its sites is dispatchable (a local jump-table "
                         "landing, a promoted near-return callee, or an owned "
                         "dispatch entry) -- so a framed switch whose arms are "
                         "unpromoted fragments is gated out, never crashing live "
                         "play with UnknownDispatchTarget.  Omit the file to "
                         "promote every dispatch optimistically (unsound).")
    ap.add_argument("--no-absorb-dispatch-arms", action="store_true",
                    help="disable dispatch-arm absorption (reproduce the "
                         "pre-cont.249 slice, where every framed tail-dispatch "
                         "container refused dyn-target-unpromoted)")
    ap.add_argument("--no-plat-farcalls", action="store_true",
                    help="disable platform far-call composition (reproduce the "
                         "pre-plat.farcall calls-only slice)")
    ap.add_argument("--overrides-out", default=str(DEFAULT_OVERRIDES),
                    help="where the authoritative-override contracts are "
                         "written (scripts/overridegen.py output, fed to the "
                         "dos_re promoter --overrides)")
    ap.add_argument("--with-overrides", action="store_true",
                    help="build the UNIFIED OVERRIDE GRAPH: the 166 "
                         "mechanically-closed hand-recovered bodies compose as "
                         "DIRECT carrier-free CPUless overrides at their own "
                         "address (impl = overrides.get(addr, generated[addr])) "
                         "instead of staying literal lifts, so their callers no "
                         "longer refuse contains-call.  Only the overrides "
                         "carrying an EXACT virtual-time contract are seeded "
                         "(cont.248) -- the rest keep their instruction-exact "
                         "generated body -- so the graph stays admissible to "
                         "the byte-exact gate.  Pair it with --graph-dir "
                         "simant/lifted/graph_cpuless_override to keep the "
                         "pinned graph untouched.")
    ap.add_argument("--overrides-any-time", action="store_true",
                    help="seed EVERY routable override, including the ones "
                         "whose per-invocation cost is path-dependent and so "
                         "run at the ISLAND cost (one dispatch step).  Maximum "
                         "manual coverage, but the graph no longer preserves "
                         "the instruction-count timeline the pinned "
                         "cold_nohooks oracle (and the instruction-count-keyed "
                         "demo) require -- cont.247 measured -16 instructions "
                         "at cp0 accumulating to -2.2M by cp31.  NOT "
                         "gate-admissible; use only with a demo re-recorded "
                         "under this exact config.")
    ap.add_argument("--skin", action="store_true",
                    help="build the SKIN corpus (task #53): the manual corpus "
                         "as CPUless skin on the generated skeleton.  Shorthand "
                         "for --with-overrides --overrides-any-time plus the "
                         "skin dirs (simant/native/cpuless_skin, "
                         "simant/lifted/graph_cpuless_skin, a skin census), so "
                         "EVERY routable hand-recovered body composes directly "
                         "while the PINNED production corpus/graph -- the ones "
                         "the instruction-count-keyed byte-exact gate runs on "
                         "-- are not touched.  The skin graph is NOT "
                         "gate-admissible (island costs); it is what "
                         "scripts/play_cpuless.py executes, and that runner has "
                         "no byte-exact oracle keyed on instruction counts.")
    ap.add_argument("--tiers", default="leaf,calls-only",
                    help="comma-separated census tiers to feed the promoter "
                         "(default: leaf,calls-only — the calls-only widening; "
                         "'leaf' alone reproduces the leaf slice). The promoter "
                         "composes bottom-up, so extra tiers only widen the "
                         "reachable set, never weaken the gate.")
    ap.add_argument("--dry-run", action="store_true",
                    help="run the promotion census only; write no files")
    args = ap.parse_args(argv)

    if args.skin:
        # The skin preset only fills in defaults the caller did not override, so
        # `--skin --graph-dir X` still works and nothing is silently redirected.
        args.with_overrides = True
        args.overrides_any_time = True
        if args.recovered_dir == str(DEFAULT_REC_DIR):
            args.recovered_dir = str(SKIN_REC_DIR)
        if args.graph_dir == str(DEFAULT_GRAPH_DIR):
            args.graph_dir = str(SKIN_GRAPH_DIR)
        if args.census_out == str(DEFAULT_CENSUS_OUT):
            args.census_out = str(SKIN_CENSUS_OUT)
        if Path(args.recovered_dir).resolve() == DEFAULT_REC_DIR.resolve():
            raise SystemExit(
                "cpuless_promote --skin: refusing to write the island-cost skin "
                "corpus into the PINNED production corpus "
                f"({DEFAULT_REC_DIR}) -- an override body would clobber the "
                "instruction-exact generated twin the byte-exact gate runs on.")

    ir = json.loads(Path(args.ir).read_text(encoding="utf-8"))
    census = json.loads(Path(args.census).read_text(encoding="utf-8"))
    map_doc = json.loads(Path(args.map).read_text(encoding="utf-8"))

    tiers = tuple(t.strip() for t in args.tiers.split(",") if t.strip())
    seg_base = para_of_seg(ir)
    manual = manual_para_keys(map_doc, seg_base)
    entries = promote_entries(census, manual, tiers)
    cand_all: set[str] = set()
    for t in tiers:
        cand_all |= {k.upper() for k in census["tiers"].get(t, [])}
    tier_sizes = ", ".join(f"{t}={len(census['tiers'].get(t, []))}"
                           for t in tiers)
    print(f"tiers [{tier_sizes}]; manual-recovered (adaptgen owns): "
          f"{len(manual & cand_all)} ∩manual; CPUless-promotion candidates "
          f"(⋃tiers ∩ ¬manual): {len(entries)}")

    rec_dir = Path(args.recovered_dir)
    import_base = import_base_of(rec_dir)
    graph_dir = Path(args.graph_dir)
    adapter_dir = graph_dir / "_adapters"        # staging for lifted_* adapters

    promote = load_dosre_tool("cpuless_promote")
    promote_argv = [
        "--ir", args.ir,
        "--recovered-dir", str(rec_dir),
        "--adapter-dir", str(adapter_dir),
        "--import-base", import_base,
        "--exclude", f"@{args.boundary_heads}",
        "--entries", ",".join(entries),
        "--census-out", args.census_out,
    ]
    # Evidence-gated dynamic dispatch: a promoted function's OBSERVED tail/near
    # dispatch targets must be dispatchable, or it is refused (never promoted to
    # crash live play with UnknownDispatchTarget).  The switch-arm fragments a
    # framed tail dispatch resolves to are unpromoted, so this gates those
    # containers out until the dispatch-cluster composition lands.
    if args.dyn_evidence and Path(args.dyn_evidence).is_file():
        promote_argv += ["--dyn-evidence", str(args.dyn_evidence)]
        # DISPATCH-ARM ABSORPTION: SIMANTW's switch arms (the SIMANTW.SYM
        # `case_XXXX` fragments) are carved as their own IR "functions" because
        # nothing but the jump table reaches them.  They are really ALTERNATE
        # ENTRIES into their container's body -- which is why each refuses
        # `leave-without-enter` standalone and, through the evidence gate,
        # held the whole message-pump dispatch cluster out of composition.
        # dos_re fuses them into their container (proving the overlap
        # byte-identical); the FACTS are the dyn evidence + the IR, both ours.
        if not args.no_absorb_dispatch_arms:
            promote_argv += ["--absorb-dispatch-arms"]
    # PLATFORM far-call composition (plat.farcall): a `call far THUNK_SEG:slot`
    # into the win16 import-thunk table becomes a platform effect, not a refusal
    # -- the gateway to the calls-only sim tier (nearly every non-trivial sim
    # function reaches an API this way).  The THUNK_SEG + per-slot argbytes are
    # a win16 fact (derived from the api registry), handed to the emitter as
    # data; dos_re stays boundary-segment-agnostic.
    if not args.no_plat_farcalls:
        thunk_seg, n_contracts, n_skipped = build_plat_farcalls(
            Path(args.manifest), Path(args.plat_farcalls_out))
        print(f"platform far-call contracts: {n_contracts} thunk slot(s) "
              f"(seg {thunk_seg:04X}); {n_skipped} skipped (raw API / gap -- "
              f"no derivable argbytes)")
        promote_argv += [
            "--plat-far-segs", f"{thunk_seg:04X}",
            "--plat-farcalls", f"@{args.plat_farcalls_out}",
        ]
    # AUTHORITATIVE OVERRIDES (the unified override-graph seam,
    # [[manual-recovery-is-authoritative]]): the mechanically-closed hand-
    # recovered bodies compose as DIRECT carrier-free CPUless overrides at their
    # own address (impl = overrides.get(addr, generated[addr])) -- so a caller
    # of a manual function no longer refuses contains-call.  overridegen emits
    # the contracts here (the bodies are dropped in AFTER --apply, so the
    # promoter's clean regen does not wipe them); the SAME adaptgen classifier
    # picks the routable set, so dos_re stays game-agnostic.
    overrides: list[str] = []
    if args.with_overrides:
        import overridegen
        og_rc = overridegen.main([
            "--ir", args.ir, "--map", args.map,
            "--out", args.overrides_out, "--dry-run",
        ])
        if og_rc != 0:
            return og_rc
        ov_doc = json.loads(
            Path(args.overrides_out).read_text(encoding="utf-8"))["overrides"]
        promote_argv += ["--overrides", f"@{args.overrides_out}"]
        if args.overrides_any_time:
            overrides = sorted(ov_doc)
            print("WARNING: --overrides-any-time seeds ISLAND-cost overrides; "
                  "the graph is NOT admissible to the instruction-count-keyed "
                  "byte-exact gate (cont.247/248).")
        else:
            # Gate-admissible subset: only the overrides whose per-invocation
            # virtual time is EXACT (overridegen derives it from the IR CFG).
            # The dos_re promoter applies the same filter when seeding, so the
            # routed adapter set and the seeded contract set stay identical.
            promote_argv += ["--overrides-time-exact-only"]
            overrides = sorted(
                k for k, v in ov_doc.items()
                if v.get("virtual_time", {}).get("kind", "island") != "island")
            print(f"overrides: {len(overrides)}/{len(ov_doc)} carry an EXACT "
                  f"virtual-time contract and are seeded; the rest stay on "
                  f"their instruction-exact generated body.")
    if args.dry_run:
        print("\n=== promotion census (dry run) ===")
        return promote.main(promote_argv)

    # Clean regen: the recovered package and the adapter staging are disposable.
    if rec_dir.exists():
        shutil.rmtree(rec_dir)
    rec_dir.mkdir(parents=True, exist_ok=True)
    adapter_dir.mkdir(parents=True, exist_ok=True)

    print("\n=== promote (emit recovered bodies + CPU-ABI adapters) ===")
    rc = promote.main(promote_argv + ["--apply"])
    if rc != 0:
        return rc
    # Package marker so the adapters' `from simant.native.cpuless.func_... import`
    # resolves.  Pure (no imports) — the recovered-purity wall covers it.
    (rec_dir / "__init__.py").write_text(
        '"""AUTOGENERATED CPUless recovered corpus (scripts/cpuless_promote.py)'
        " -- disposable; regenerate, do not hand-edit.\"\"\"\n",
        encoding="utf-8", newline="\n")

    # Drop the carrier-free override BODIES into the recovered corpus (AFTER the
    # promoter's clean regen, so they survive); the override ADAPTERS were
    # already emitted by the dos_re promoter (--overrides) into adapter_dir.
    if args.with_overrides:
        import overridegen
        print("\n=== emit carrier-free CPUless override bodies ===")
        og_rc = overridegen.main([
            "--ir", args.ir, "--map", args.map,
            "--bodies-dir", str(rec_dir), "--out", args.overrides_out,
        ] + ([] if args.overrides_any_time else ["--only-time-exact"]))
        if og_rc != 0:
            return og_rc

    promoted = json.loads(
        Path(args.census_out).read_text(encoding="utf-8"))["promotable"]
    print("\n=== route the CPUless-routed graph "
          f"({graph_dir.relative_to(REPO_ROOT).as_posix()}) ===")
    routed, missing = route_graph(Path(args.from_dir), graph_dir, adapter_dir,
                                  promoted, overrides)
    shutil.rmtree(adapter_dir)                    # staging consumed
    if missing:
        raise SystemExit(f"cpuless_promote: {len(missing)} promoted leaf/leaves "
                         f"had no emitted adapter: {missing[:8]}")
    print(f"routed {routed} CPUless adapter(s) into {graph_dir.name}; the rest "
          f"stay literal lifts")

    print("\n=== CPUless recovered-purity wall (lint_cpuless) ===")
    rc = run_lint(rec_dir, import_base)
    if rc != 0:
        print("CPUless wall: FAIL")
        return rc
    print(f"\nCPUless slice complete: {len(promoted)} leaf function(s) promoted "
          f"to pure-Python recovered bodies + CPU-ABI adapters; wall holds.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
