"""dispatchgen — mechanically derive SIMANTW's switch-dispatch entry facts.

The VMless-wall closure step for jmp_ind TAIL dispatchers
(win16_re/dos_re/docs/dos_re_2.0.md §1a): a lifted dispatcher body ends at
``jmp word ptr cs:[bx+TABLE]`` by setting CS:IP to the runtime case target and
handing control back to the step dispatch — so under the armed interpreter
poison EVERY possible case target must itself be a census entry with an
installed lifted hook.  This tool derives those targets MECHANICALLY, with the
table bounds PROVEN from the dispatcher's own guard code, and writes them as
evidence-backed recovery facts:

    simant/facts/dispatch_entries.txt   one NE_SEG:OFFSET per distinct case
                                        target (consumed by scripts/irgen.py as
                                        additional census entries)
    simant/facts/code_as_data.txt       the jump-table byte ranges (data inside
                                        code segments: preserved by the boot-
                                        image poison and declared to its audit)

Derivation (MSC C 6/7 switch codegen, three observed guard families — each
site must prove one exactly, else the dispatcher is STOPPED and reported, never
guessed):

    F1  cmp ax,N / ja DEFAULT / shl ax,1 / xchg ax,bx / jmp cs:[bx+T]
        -> N+1 case slots (index compared, then scaled)
    F2  cmp ax,N / jbe +3 / jmp DEFAULT / shl ax,1 / xchg ax,bx / jmp ...
        -> N+1 case slots (inverted guard)
    F3  cmp ax,N / ja DEFAULT / xchg ax,bx / jmp cs:[bx+T]   (no shl)
        -> N even, N/2+1 case slots (the compared value is already the
           scaled BYTE offset — _GBoxFill's pattern-code family)

Table words are read from the loaded image (the same bytes the dispatcher
reads at run time).  Dispatchers whose jmp_ind is NOT the table idiom (the CRT
register-indirect tails: ``jmp [di]``, ``jmp bx``, chkstk's far returns) are
reported: their runtime targets are census entries or emulated-call return
continuations, both already covered by the step dispatch — the runtime
frontier audit (scripts/play_vmless.py --collect-frontier) is the proof.

    python scripts/dispatchgen.py [--ir artifacts/recovery_ir.json] [--check]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

import simant._env  # noqa: E402,F401
import win16  # noqa: E402,F401

DEFAULT_IR = REPO_ROOT / "artifacts" / "recovery_ir.json"
FACTS_DIR = REPO_ROOT / "simant" / "facts"

_NOTICE = ("# GENERATED by scripts/dispatchgen.py -- evidence-backed recovery facts.\n"
           "# Regenerate: python scripts/dispatchgen.py   (deterministic; do not hand-edit\n"
           "# except to remove a fact together with the dispatcher change that voids it).\n")


class DispatchStop(Exception):
    """A dispatcher whose table bounds are not provable — reported, not guessed."""


def _inst_map(rec: dict) -> dict[int, dict]:
    return {int(i["ip"], 16): i
            for b in rec["blocks"] for i in b["instructions"]}


def _back_chain(insts: dict[int, dict], ip: int, depth: int) -> list[dict]:
    """Up to ``depth`` instructions ending exactly AT ``ip``, oldest first —
    the unique byte-adjacent predecessor chain (stops early at a join)."""
    chain: list[dict] = []
    cur = ip
    for _ in range(depth):
        preds = [i for p, i in insts.items()
                 if p + len(i["bytes"]) // 2 == cur and p != cur]
        if len(preds) != 1:
            break
        chain.append(preds[0])
        cur = int(preds[0]["ip"], 16)
    chain.reverse()
    return chain


def derive_site(rec: dict, insts: dict[int, dict], site_ip: int,
                fetch) -> dict:
    """Prove one jmp_ind site's table bounds and read its targets.

    Returns {"family", "table", "bound_imm", "guard_ip", "slots", "targets"}.
    Raises DispatchStop when no family matches exactly."""
    jmp = insts[site_ip]
    b = bytes.fromhex(jmp["bytes"])
    if not (len(b) == 5 and b[:3] == bytes.fromhex("2effa7")):
        raise DispatchStop(f"non-table jmp_ind ({jmp['mnemonic']} {jmp['bytes']})")
    table = int.from_bytes(b[3:5], "little")

    chain = _back_chain(insts, site_ip, 5)

    def raw(i: dict) -> bytes:
        return bytes.fromhex(i["bytes"])

    if len(chain) < 2 or raw(chain[-1]) != b"\x93":
        raise DispatchStop("no `xchg ax,bx` before the table jmp")

    def _cmp_imm(i: dict) -> int:
        rb = raw(i)
        if len(rb) == 3 and rb[0] == 0x3D:            # cmp ax, imm16
            return int.from_bytes(rb[1:3], "little")
        raise DispatchStop(f"guard compare is not `cmp ax,imm16` ({i['mnemonic']} {i['bytes']})")

    if len(chain) >= 3 and raw(chain[-2]) == b"\xd1\xe0":     # shl ax,1
        g = chain[-3]
        if raw(g)[:1] == b"\x77":                             # F1: ja DEFAULT
            if len(chain) < 4:
                raise DispatchStop("F1: no compare before the `ja` guard")
            imm = _cmp_imm(chain[-4])
            fam, guard = "F1", g
        elif g["kind"] == "jmp":                              # F2: jbe +3 / jmp DEFAULT
            if len(chain) < 5 or raw(chain[-4])[:1] != b"\x76":
                raise DispatchStop("F2: `jmp DEFAULT` not guarded by `jbe`")
            jbe = chain[-4]
            if int(jbe.get("target", "-1"), 16) != int(chain[-2]["ip"], 16):
                raise DispatchStop("F2: `jbe` does not enter the dispatch sequence")
            imm = _cmp_imm(chain[-5])
            fam, guard = "F2", jbe
        else:
            raise DispatchStop(f"unrecognized guard before shl ({g['mnemonic']} {g['bytes']})")
        slots = imm + 1
    elif raw(chain[-2])[:1] == b"\x77":                        # F3: ja, no shl
        if len(chain) < 3:
            raise DispatchStop("F3: no compare before the `ja` guard")
        imm = _cmp_imm(chain[-3])
        if imm % 2:
            raise DispatchStop(f"F3: scaled compare bound {imm:#x} is odd")
        fam, guard = "F3", chain[-2]
        slots = imm // 2 + 1
    else:
        raise DispatchStop(
            f"no table-guard idiom before the jmp "
            f"({' '.join(i['bytes'] for i in chain[-3:])})")

    targets = [fetch(table + 2 * k) | (fetch(table + 2 * k + 1) << 8)
               for k in range(slots)]
    return {"family": fam, "table": table, "bound_imm": imm,
            "guard_ip": guard["ip"], "slots": slots, "targets": targets}


def derive_all(ir: dict, fetch_for) -> tuple[list[dict], list[dict]]:
    """(derived site records, stopped site records) over every liftable
    jmp_ind-tailed function of the IR."""
    derived: list[dict] = []
    stopped: list[dict] = []
    seen_sites: set[tuple[int, int]] = set()
    for entry in sorted(ir["functions"]):
        rec = ir["functions"][entry]
        if not rec.get("liftable") or "jmp_ind" not in rec.get("exits", ()):
            continue
        cs = int(entry.split(":")[0], 16)
        insts = _inst_map(rec)
        for ip in sorted(insts):
            if insts[ip]["kind"] != "jmp_ind" or (cs, ip) in seen_sites:
                continue
            seen_sites.add((cs, ip))
            base = {"entry": entry, "symbol": rec.get("symbol", "?"),
                    "ne_seg": rec["ne_seg"], "cs": cs, "site_ip": ip}
            try:
                base.update(derive_site(rec, insts, ip, fetch_for(cs)))
                derived.append(base)
            except DispatchStop as exc:
                base["reason"] = str(exc)
                stopped.append(base)
    return derived, stopped


def render_facts(ir: dict, derived: list[dict]) -> tuple[str, str]:
    """(dispatch_entries.txt, code_as_data.txt) content from derived sites."""
    by_target: dict[tuple[int, int], list[str]] = {}
    for d in derived:
        for k, tgt in enumerate(d["targets"]):
            key = (d["ne_seg"], tgt)
            via = (f"{d['symbol']}@{d['site_ip']} case {k}/{d['slots'] - 1} "
                   f"({d['family']} table={d['table']:04X} "
                   f"cmp@{d['guard_ip']} imm={d['bound_imm']:#x})")
            by_target.setdefault(key, []).append(via)

    lines = [_NOTICE,
             "# Case-body census entries for the jmp_ind switch dispatchers:",
             "# every possible runtime target of a proven-bound jump table, so the",
             "# lifted graph covers each with an installed hook (VMless wall)."]
    n_new = 0
    for (seg, off), vias in sorted(by_target.items()):
        d0 = next(d for d in derived if d["ne_seg"] == seg)
        key = f"{d0['cs']:04X}:{off:04X}"
        rec = ir["functions"].get(key)
        # A target that is a census entry INDEPENDENTLY of this facts file
        # (.SYM symbol / closure / hand fact) needs no new fact; one whose
        # record exists because a PREVIOUS run of this generator declared it
        # (entry_origin dispatch-fact) must be re-emitted, or regeneration
        # would oscillate (the fact file is the source of those records).
        if rec is not None and rec.get("entry_origin") != "dispatch-fact":
            lines.append(f"# {seg}:{off:04X} is already census entry "
                         f"{rec.get('symbol', key)} -- via {vias[0]}")
            continue
        n_new += 1
        lines.append(f"{seg}:{off:04X}  # via {'; '.join(vias)}")
    entries_txt = "\n".join(lines) + "\n"

    tlines = [_NOTICE,
              "# Jump-table byte ranges (DATA inside code segments): preserved by the",
              "# boot-image poison and declared to its audit as code_as_data.",
              "# Format: NE_SEG:HEX_OFFSET+HEX_LENGTH"]
    seen = set()
    for d in sorted(derived, key=lambda d: (d["ne_seg"], d["table"])):
        key = (d["ne_seg"], d["table"], d["slots"])
        if key in seen:
            continue
        seen.add(key)
        tlines.append(f"{d['ne_seg']}:{d['table']:04X}+{2 * d['slots']:X}  "
                      f"# switch table of {d['symbol']}@{d['site_ip']} "
                      f"({d['slots']} slots, {d['family']})")
    tables_txt = "\n".join(tlines) + "\n"
    return entries_txt, tables_txt, n_new


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ir", default=str(DEFAULT_IR))
    ap.add_argument("--check", action="store_true",
                    help="verify the committed facts files match a fresh "
                         "derivation (exit 1 on drift)")
    args = ap.parse_args(argv)

    from simant.runtime import create_machine
    ir = json.loads(Path(args.ir).read_text(encoding="utf-8"))
    machine = create_machine()
    mem = machine.mem

    def fetch_for(cs: int):
        return lambda off: mem.rb(cs, off & 0xFFFF)

    derived, stopped = derive_all(ir, fetch_for)
    entries_txt, tables_txt, n_new = render_facts(ir, derived)

    n_slots = sum(d["slots"] for d in derived)
    print(f"dispatchgen: {len(derived)} table sites proven "
          f"({n_slots} slots, {n_new} new census entries), "
          f"{len(stopped)} sites stopped")
    fam = {}
    for d in derived:
        fam[d["family"]] = fam.get(d["family"], 0) + 1
    print("  families: " + ", ".join(f"{k}={v}" for k, v in sorted(fam.items())))
    for s in stopped:
        print(f"  STOP {s['entry']} {s['symbol']} @{s['site_ip']:04X}: {s['reason']}")

    ent_path = FACTS_DIR / "dispatch_entries.txt"
    tab_path = FACTS_DIR / "code_as_data.txt"
    if args.check:
        drift = []
        for path, txt in ((ent_path, entries_txt), (tab_path, tables_txt)):
            if not path.exists() or path.read_text(encoding="utf-8") != txt:
                drift.append(path.name)
        if drift:
            print(f"CHECK FAIL: committed facts drift from fresh derivation: "
                  f"{', '.join(drift)} -- rerun scripts/dispatchgen.py")
            return 1
        print("CHECK OK: committed facts match a fresh derivation")
        return 0
    ent_path.write_text(entries_txt, encoding="utf-8")
    tab_path.write_text(tables_txt, encoding="utf-8")
    print(f"wrote {ent_path} and {tab_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
