"""irgen — SIMANTW's recovery IR: every SIMANTW.SYM entry, one JSON document.

The DOS_RE 2.0 serialization step (win16_re/dos_re/docs/recovery_ir.md) for
SimAnt: resolves ALL named routines in SIMANTW.SYM's code segments (the same
1319-entry corpus scripts/census.py sweeps), runs the generic win16 irgen
front-end over a loaded machine, and writes the deterministic, regeneratable
``artifacts/recovery_ir.json`` (gitignored — a generated artifact, never
committed; delete it and this script reproduces it byte-identically).

Game facts live in simant/facts/ as committed text (NE_SEG:HEX_OFFSET per
line + comments): keep_interpreted.txt lists the environment-wait facts (the
x87 + _DoInt3 census scan frontier), tagged env_wait in the IR.  Symbol identity is first-class: every
record carries symbol/module/ne_seg from the .SYM (and alias names where two
symbols share an address) alongside its canonical paragraph-base CS:IP key,
and the .SYM sha1 lands in provenance next to the EXE's.

The census is CLOSED over runtime control flow (the VMless-wall requirement —
every address the step dispatch can land on carries a hook):

* **dispatch case entries** — simant/facts/dispatch_entries.txt (generated by
  scripts/dispatchgen.py, evidence-backed): every proven jump-table target of
  the jmp_ind switch dispatchers becomes a census entry, identity
  ``case_<OFF>`` with ``entry_origin: dispatch-fact``;
* **static-call closure** — near/far CALL targets inside the code segments
  that are not .SYM entries (CRT-internal labels) are discovered mechanically
  by a static fixpoint scan and added as ``internal_<OFF>`` entries with
  ``entry_origin: static-call-closure``.

    python scripts/irgen.py [--snapshot DIR] [--seg N ...] [--no-probe]
                            [--out artifacts/recovery_ir.json]
"""
from __future__ import annotations

import argparse
import hashlib
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

import simant._env  # noqa: E402,F401
import win16  # noqa: E402,F401

from win16.irgen import build_ir, write_document  # noqa: E402
from simant.probes.symbols import _SYM_PATH, _segments  # noqa: E402
from simant.runtime import create_machine  # noqa: E402

#: NE segments holding game CODE (4=_TEXT is the C runtime, also code) —
#: the same corpus as scripts/census.py.
CODE_SEGS = (1, 2, 3, 4, 5, 6, 7)

FACTS_DIR = REPO_ROOT / "simant" / "facts"
DEFAULT_OUT = REPO_ROOT / "artifacts" / "recovery_ir.json"


def read_fact_pairs(path: Path) -> list[tuple[int, int]]:
    """NE pairs from a facts file: 'NE_SEG:HEX_OFFSET  # comment' per line
    (segment index decimal, offset hex).  A trailing word (the boundary-head
    park KIND — see read_fact_pairs_kinded) is ignored here: an address is an
    address whatever policy rides with it."""
    return [pair for pair, _kind in read_fact_pairs_kinded(path)]


def read_fact_pairs_kinded(path: Path) -> list[tuple[tuple[int, int], str | None]]:
    """((ne_seg, off), kind|None) per line: 'NE_SEG:HEX_OFFSET [kind] #...'.

    The optional trailing word is the head's INTERACTIVE PARK COST
    (win16.interactive FRAME_GATE / PACING_SPIN — a runtime policy, not
    something the IR or the emitter knows: emission is identical either
    way).  None = the host's default."""
    out: list[tuple[tuple[int, int], str | None]] = []
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        seg, off = parts[0].split(":", 1)
        kind = parts[1] if len(parts) > 1 else None
        if len(parts) > 2:
            raise ValueError(f"{path.name}: cannot parse {line!r}")
        out.append(((int(seg, 10), int(off, 16) & 0xFFFF), kind))
    return out


def sym_corpus(segs=CODE_SEGS):
    """(entries, names): every SIMANTW.SYM entry of the code segments, sorted
    by (seg, offset), plus its identity metadata.  Two symbols may alias one
    address (e.g. __aFftol/__ftol) — the first (sorted) name is `symbol`, the
    rest become `aliases`; the address is scanned once."""
    entries: list[tuple[int, int]] = []
    names: dict[tuple[int, int], dict] = {}
    n_syms = 0
    for seg_i, (modname, syms) in enumerate(_segments(), start=1):
        if seg_i not in segs or not syms:
            continue
        for off, name in syms:              # sorted by (offset, name)
            n_syms += 1
            key = (seg_i, off)
            if key in names:
                names[key].setdefault("aliases", []).append(name)
                continue
            entries.append(key)
            names[key] = {"symbol": name, "module": modname}
    return entries, names, n_syms


def _module_of_seg() -> dict[int, str]:
    """NE segment index -> .SYM module name (identity for generated entries)."""
    return {i: modname for i, (modname, _syms)
            in enumerate(_segments(), start=1)}


def add_dispatch_entries(entries, names, segs) -> int:
    """Append the dispatch case-body facts (scripts/dispatchgen.py) and the
    hand-verified indirect-target facts as census entries with generated
    identity.  Returns how many."""
    mod_of = _module_of_seg()
    added = 0
    for fname, prefix, origin in (
            ("dispatch_entries.txt", "case", "dispatch-fact"),
            ("indirect_targets.txt", "indirect", "indirect-target-fact")):
        for seg, off in read_fact_pairs(FACTS_DIR / fname):
            key = (seg, off)
            if seg not in segs or key in names:
                continue
            entries.append(key)
            names[key] = {"symbol": f"{prefix}_{off:04X}",
                          "module": mod_of[seg], "entry_origin": origin}
            added += 1
    return added


def close_static_call_targets(machine, entries, names, segs,
                              build) -> int:
    """Static-call census closure: fixpoint over near/far CALL targets that
    land inside the code segments but are not census entries yet (the
    CRT-internal labels).  ``build`` runs a STATIC-only build_ir over the
    current entry list; discovered targets join the census as
    ``internal_<OFF>`` and the scan repeats until no new target appears.
    Mechanically derived — no fact file (docs/dos_re_2.0.md: facts are only
    for what tooling cannot derive)."""
    seg_of_para = {machine.seg_bases[i]: i
                   for i in range(1, len(machine.seg_bases))
                   if machine.seg_bases[i]}
    mod_of = _module_of_seg()
    known = set(names)
    total = 0
    while True:
        doc = build(entries)
        missing: set[tuple[int, int]] = set()
        for entry, rec in doc["functions"].items():
            if not rec.get("liftable"):
                continue                      # refused scans carry no reliable edges
            cs = int(entry.split(":")[0], 16)
            ne_seg = seg_of_para.get(cs)
            for tgt in rec.get("calls_near", ()):
                pair = (ne_seg, int(tgt, 16))
                if pair[0] in segs and pair not in known:
                    missing.add(pair)
            for seg_hex, off_hex in rec.get("calls_far", ()):
                far_seg = seg_of_para.get(int(seg_hex, 16))
                if far_seg is None:           # import thunk / equate — not game code
                    continue
                pair = (far_seg, int(off_hex, 16))
                if pair[0] in segs and pair not in known:
                    missing.add(pair)
        if not missing:
            return total
        for seg, off in sorted(missing):
            entries.append((seg, off))
            names[(seg, off)] = {"symbol": f"internal_{off:04X}",
                                 "module": mod_of[seg],
                                 "entry_origin": "static-call-closure"}
            known.add((seg, off))
            total += 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--snapshot", default=None,
                    help="build the IR over this vmsnap snapshot instead of "
                         "a fresh create_machine() boot image")
    ap.add_argument("--seg", type=int, action="append", default=[],
                    help="restrict to these NE segments (repeatable)")
    ap.add_argument("--no-probe", action="store_true",
                    help="static-only scan (skip the per-entry interpreter "
                         "step-length probe; faster, decoder unchecked)")
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args(argv)
    segs = tuple(args.seg) or CODE_SEGS

    if args.snapshot:
        from win16.vmsnap import load_snapshot
        machine = load_snapshot(args.snapshot, create_machine)
        snapshot_desc = str(args.snapshot)
    else:
        machine = create_machine()
        snapshot_desc = "(fresh create_machine boot image)"
    machine.cpu.trace_enabled = False

    entries, names, n_syms = sym_corpus(segs)
    keep = [p for p in read_fact_pairs(FACTS_DIR / "keep_interpreted.txt")
            if p[0] in segs]
    # Boundary heads: the hand-curated evidence-promoted waits PLUS the
    # mechanically derived pure-wait enumeration (scripts/waitscan.py).
    heads = [p for f in ("boundary_heads.txt", "boundary_heads_derived.txt")
             for p in read_fact_pairs(FACTS_DIR / f) if p[0] in segs]
    sym_kw = dict(
        environment_wait_entries=keep,
        boundary_heads=heads,
        snapshot=snapshot_desc,
        symbols=f"{_SYM_PATH.name} sha1="
                f"{hashlib.sha1(_SYM_PATH.read_bytes()).hexdigest()}",
    )

    t0 = time.perf_counter()
    n_dispatch = add_dispatch_entries(entries, names, segs)
    n_internal = close_static_call_targets(
        machine, entries, names, segs,
        build=lambda ents: build_ir(machine, ents, machine_factory=None,
                                    names=names, **sym_kw))
    doc = build_ir(
        machine, entries,
        machine_factory=None if args.no_probe else create_machine,
        names=names,
        **sym_kw,
    )
    dt = time.perf_counter() - t0
    out = write_document(doc, args.out)

    functions, unsupported = doc["functions"], doc["unsupported"]
    n_liftable = sum(1 for f in functions.values() if f["liftable"])
    n_unsupported_fns = len({u["entry"] for u in unsupported})
    print(f"recovery IR v{doc['ir_version']}: {n_syms} SYM entries "
          f"+ {n_dispatch} dispatch-fact case entries "
          f"+ {n_internal} static-call-closure entries -> "
          f"{len(functions)} functions ({n_liftable} liftable, "
          f"{n_unsupported_fns} unsupported over {len(unsupported)} refusal "
          f"records) in {dt:.1f}s -> {out}")
    if unsupported:
        print("unsupported ledger (the fail-loud frontier):")
        seen = set()
        for u in unsupported:
            if u["entry"] in seen:
                continue
            seen.add(u["entry"])
            fn = functions[u["entry"]]
            label = "/".join([fn.get("symbol", "?")] + fn.get("aliases", []))
            print(f"  {u['entry']} seg{fn['ne_seg']} "
                  f"{fn.get('module', '?')}!{label}: {u['reason']} "
                  f"({u['detail']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
