"""liftemit — batch-emit SIMANTW's full VMless lifted graph from the recovery IR.

The M2 bulk-emission step of the DOS_RE 2.0 adoption
(win16_re/dos_re/docs/dos_re_2.0.md): every liftable record of
``artifacts/recovery_ir.json`` (scripts/irgen.py) becomes one SYMBOLICALLY
NAMED VMless module in ``--emit-dir`` — ``simone_srand1.py`` defining
``simone_srand1``, named from the record's first-class .SYM identity — with
the entry->stem mapping persisted as ``graph_manifest.json`` (the
``dos_re.lift.naming`` seam the link/install machinery resolves through).
The paragraph-base address stays inside each module as provenance (the
``ENTRY`` constant + the AUTOGENERATED header).

Every module is emitted ``count_instructions=True`` (virtual-time
preservation): the instruction-count timeline of the assembled graph is
IDENTICAL to the interpreted oracle's, which is what keeps instruction-keyed
demos and checkpoint traces comparable across the two runtimes.

The emitted corpus is DISPOSABLE generated output (gitignored): delete it and
this script reproduces it from the IR alone.  Never hand-edit a module —
fix the emitter or the facts and regenerate.

    python scripts/liftemit.py [--ir artifacts/recovery_ir.json]
                               [--emit-dir simant/lifted/graph]
                               [--seg N ...] [--require-vmless-wall]
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import keyword
import re
import sys
import time
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

import simant._env  # noqa: E402,F401
import win16  # noqa: E402,F401  (puts the nested dos_re on sys.path)

import dos_re  # noqa: E402
from dos_re.lift.naming import GraphNaming  # noqa: E402

DEFAULT_IR = REPO_ROOT / "artifacts" / "recovery_ir.json"
DEFAULT_EMIT_DIR = REPO_ROOT / "simant" / "lifted" / "graph"


def boundary_heads_from_ir(doc: dict) -> frozenset[tuple[int, int]]:
    """The boundary-head facts, as paragraph-base (cs, ip) pairs, read from
    the IR's own ``facts_applied`` record (scripts/irgen.py applies
    simant/facts/boundary_heads.txt there) — ONE source, no re-conversion.
    Passing them to the emitter turns on the host-side observer events +
    RESUME entries AND, non-empty, pipeline-wide ``resume_calls`` (the unwind
    re-entry rule — every call-site continuation must be a resume entry)."""
    return frozenset(
        (int(cs, 16), int(ip, 16))
        for cs, ip in (key.split(":")
                       for key in doc.get("facts_applied", {})
                                     .get("boundary_heads", ())))


def load_dosre_tool(name: str):
    """Import a dos_re tools/*.py module by file path (tools/ is not a
    package; this is the same mechanism dos_re's own tests use)."""
    tools = Path(dos_re.__file__).resolve().parents[1] / "tools"
    spec = importlib.util.spec_from_file_location(f"dosre_{name}",
                                                  tools / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# --- the symbolic naming policy (SimAnt owns this; dos_re only serves it) -------

def _sanitize(text: str) -> str:
    out = re.sub(r"[^0-9a-z_]+", "_", text.lower()).strip("_")
    return out


def stem_for(rec: dict) -> str:
    """``{module}_{symbol}`` in lower snake case: SIMONE_MODULE!_SRand1 ->
    ``simone_srand1`` (collisions get an address suffix in build_naming)."""
    mod = _sanitize(rec["module"]).removesuffix("_module") or f"seg{rec['ne_seg']}"
    sym = _sanitize(rec["symbol"]) or "anon"
    stem = f"{mod}_{sym}"
    if not stem[0].isalpha():
        stem = f"f_{stem}"
    if keyword.iskeyword(stem):
        stem += "_"
    return stem


def build_naming(functions: dict[str, dict]) -> GraphNaming:
    """Deterministic entry->stem map for every LIFTABLE record.  Any stem
    claimed by more than one address gets the entry offset appended to EVERY
    claimant (deterministic, order-independent)."""
    liftable = {e: r for e, r in functions.items() if r.get("liftable")}
    raw = {entry: stem_for(rec) for entry, rec in sorted(liftable.items())}
    counts = Counter(raw.values())
    mapping = {}
    for entry, stem in raw.items():
        if counts[stem] > 1:
            stem = f"{stem}_{entry.split(':')[1].lower()}"
        mapping[entry] = stem
    return GraphNaming(mapping)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ir", default=str(DEFAULT_IR))
    ap.add_argument("--emit-dir", default=str(DEFAULT_EMIT_DIR))
    ap.add_argument("--seg", type=int, action="append", default=[],
                    help="restrict to these NE segments (subset builds)")
    ap.add_argument("--max-iterations", type=int, default=5_000_000,
                    help="runaway-guard floor baked into each module.  SimAnt "
                         "paces by spinning on GetTickCount, and the demo "
                         "clock derives ticks from the instruction count -- "
                         "the spins are virtual-time-bounded, but a seconds-"
                         "long wait legitimately needs ~170k loop iterations "
                         "per second (found live: _WaitHundredths).  A truly "
                         "unbounded loop still fails loud, just later.")
    ap.add_argument("--require-vmless-wall", action="store_true",
                    help="fail (exit 2) if any emitted module contains an "
                         "interp_one fallback call site")
    args = ap.parse_args(argv)

    liftemit = load_dosre_tool("liftemit")

    doc = json.loads(Path(args.ir).read_text(encoding="utf-8"))
    functions = doc["functions"]
    if args.seg:
        functions = {e: r for e, r in functions.items()
                     if r["ne_seg"] in set(args.seg)}

    emit_dir = Path(args.emit_dir)
    emit_dir.mkdir(parents=True, exist_ok=True)
    # The corpus is disposable generated output: regenerate from scratch so a
    # renamed/removed entry never leaves a stale module behind to install.
    for old in emit_dir.glob("*.py"):
        old.unlink()

    naming = build_naming(functions)
    naming.save(emit_dir)

    heads = boundary_heads_from_ir(doc)
    if heads:
        print(f"boundary heads (facts_applied): "
              + ", ".join(f"{cs:04X}:{ip:04X}" for cs, ip in sorted(heads))
              + " -- observer events + RESUME entries emitted; resume_calls "
                "pipeline-wide")

    t0 = time.perf_counter()
    counts = Counter()
    per_seg = Counter()
    skipped: list[tuple[str, str, str, str]] = []
    for entry in sorted(functions):
        rec = functions[entry]
        status, detail = liftemit.emit_entry_from_ir(
            rec, emit_dir, args.max_iterations,
            boundary_heads=heads,
            stem=naming.stem_of(entry) if rec.get("liftable") else None)
        counts[status] += 1
        if status == "ok":
            per_seg[rec["ne_seg"]] += 1
        else:
            skipped.append((entry, rec.get("symbol", "?"), status, detail))
    dt = time.perf_counter() - t0

    print(f"emitted {counts['ok']}/{len(functions)} modules to {emit_dir} "
          f"in {dt:.1f}s (not-liftable={counts['not-liftable']}, "
          f"emit-unsupported={counts['emit-unsupported']})")
    print("per NE segment: " + ", ".join(
        f"seg{s}={n}" for s, n in sorted(per_seg.items())))
    if skipped:
        print("skipped (the fail-loud frontier — every one a queue entry):")
        for entry, symbol, status, detail in skipped:
            print(f"  {entry} {symbol}: {status} ({detail})")

    offenders = liftemit.vmless_wall_report(emit_dir)
    if offenders:
        total = sum(offenders.values())
        print(f"VMless wall: {total} interp_one fallback call site(s) in "
              f"{len(offenders)} module(s):")
        for name, n in sorted(offenders.items()):
            print(f"  {name}: {n}")
        if args.require_vmless_wall:
            print("--require-vmless-wall: FAIL")
            return 2
    else:
        print("VMless wall: HOLDS (0 interp_one call sites in the corpus)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
