"""overridegen -- emit the CARRIER-FREE CPUless override bodies + contracts.

The unified-override-graph seam (owner's directive; docs/run_status.md cont.247):
every SimAnt function has a GENERATED CPUless identity, and where a verified
hand-recovered body exists in ``simant/recovered/`` it OVERRIDES at the SAME
address in ONE unified CPUless graph --

    implementation = manual_overrides.get(addr, generated[addr])

This is the CPUless-idiom analogue of ``scripts/adaptgen.py``: it shares
adaptgen's EXACT contract classifier (:func:`adaptgen.classify` over
``simant/facts/recovered_map.json`` + the recovery IR + ``adapter_facts.json``),
so the SAME 166 mechanically-closed entries route -- but instead of a CPU-carrier
adapter (``def adapter(cpu):`` reading ``cpu.s``/``cpu.mem``), it emits a
CARRIER-FREE marshalling shim that obeys the dos_re CPUless BODY ABI

    func_CCCC_IIII(mem, *, ds=0, ss=0, sp=0) -> (outputs, compat)

operating on the CPUless caller's EXPLICIT state (the mem image + the register
bundle the CPUless convention passes), NEVER a ``cpu`` object.  The shim:

  (a) reads each ``[bp+N]`` scalar arg off the CPUless caller's stack
      (``mem.rw(ss, sp + N - 2)`` -- at CPUless callee entry ``ss:sp`` points at
      the return frame, exactly as at the historical hook entry),
  (b) binds the dgroup / simant_data_group / pack views over that SAME mem image
      (``SelectorBackend(mem, ...)`` -- duck-typed, VM-free),
  (c) calls the authoritative hand-recovered body,
  (d) returns its AX / DX:AX result in the CPUless output dict,
  (e) leaves the ret/stack effect to the composing caller (the contract's
      ret_kind/ret_pop, applied by dos_re's override-call composition).

Because the shim reaches no ``dos_re.cpu`` and no ``simant.lifted``, it PASSES
``lint_cpuless`` -- it lives in the recovered corpus (``simant/native/cpuless/``)
as the body dos_re's ``cpuless_promote --overrides`` seeds a contract for and
every caller composes.

VIRTUAL TIME: an override is ONE dispatch step (``cost=1``), the island
convention every hand-recovered body has followed since the first -- not the
generated body's instruction-exact timeline.  The boot-image gate samples at API
boundaries where that difference is not observable (the 402 generated adapters
already ride it).

Emits, for each routed entry:
  * ``<bodies-dir>/func_<para>_<ip>.py``  -- the carrier-free override body
  * an entry in ``<out>`` (overrides.json)  -- the dos_re override contract

Every entry adaptgen keeps on the literal lift (args-incomplete, presentation-
effects, gated, sig-mismatch, ...) stays on the GENERATED body -- reported here
with the same reason, unchanged.  Run AFTER the dos_re promoter's --apply (which
regenerates simant/native/cpuless); this drops the override bodies in beside the
generated corpus, so they are not wiped.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "scripts"))

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

import simant._env  # noqa: E402,F401
import win16  # noqa: E402,F401

import adaptgen  # noqa: E402  (the shared contract classifier)

DEFAULT_IR = REPO_ROOT / "artifacts" / "recovery_ir.json"
DEFAULT_MAP = REPO_ROOT / "simant" / "facts" / "recovered_map.json"
DEFAULT_FACTS = REPO_ROOT / "simant" / "facts" / "adapter_facts.json"
DEFAULT_BODIES = REPO_ROOT / "simant" / "native" / "cpuless"
DEFAULT_OUT = REPO_ROOT / "artifacts" / "overrides.json"
DEFAULT_REPORT = REPO_ROOT / "artifacts" / "override_report.json"

#: DGROUP pointer globals holding the other two fixed NE data segments'
#: selectors (load-time relocation constants; see simant/hooks.py + adaptgen).
SDG_PTR_GLOBAL = 0xC49A     # -> SIMANT_DATA_GROUP (NE seg 8)
PACK_PTR_GLOBAL = 0xC49C    # -> PACK (NE seg 9)

#: view name -> the (mem-local) SelectorBackend binding expression.
VIEW_BIND = {
    "dgroup": "SelectorBackend(mem, ds)",
    "simant_data_group": f"SelectorBackend(mem, mem.rw(ds, {SDG_PTR_GLOBAL:#06x}))",
    "pack": f"SelectorBackend(mem, mem.rw(ds, {PACK_PTR_GLOBAL:#06x}))",
}
_VIEW_VAR = {"dgroup": "dgroup", "simant_data_group": "sdg", "pack": "pack"}


def emit_body(c: dict) -> str:
    """Source of one carrier-free CPUless override body (function name matches
    the dos_re contract: ``func_<para>_<ip>``)."""
    modname, fnname = c["impl"].rsplit(".", 1)
    stem = f"func_{c['para_key'].replace(':', '_').lower()}"
    views = c["views"]
    args = c["args"]
    L: list[str] = []
    A = L.append
    A('"""AUTOGENERATED by scripts/overridegen.py -- carrier-free CPUless OVERRIDE')
    A("body (the unified override-graph seam).  DO NOT hand-edit: regenerate from")
    A("recovered_map.json + recovery_ir.json + adapter_facts.json.")
    A("")
    A(f"{c['key']} {c['symbol']} -> {c['impl']}")
    A(f"ABI: {c['ret']} return, views {views},")
    A(f"     args {[(n, f'[bp+{bp}]') for n, bp in args]}, result -> {c['result']}")
    A("")
    A("Obeys the dos_re CPUless body ABI (mem + register bundle -> outputs,")
    A("compat); reaches no dos_re.cpu / cpu.s -- it is composed as a DIRECT")
    A('override, not a CPU-carrier adapter."""')
    A("from __future__ import annotations")
    A("")
    if views:
        A("from simant.bridge.dgroup_view import SelectorBackend")
    A(f"from {modname} import {fnname} as _impl")
    A("")
    if args:
        A("")
        A("def _sx(v):")
        A("    return v - 0x10000 if v & 0x8000 else v")
        A("")
    A("")
    # inputs: ds when a view is bound; ss/sp when a stack arg is read.
    params = []
    if views:
        params.append("ds=0")
    if args:
        params += ["ss=0", "sp=0"]
    A(f"def {stem}(mem, *, {', '.join(params)}):")
    A(f'    """Carrier-free CPUless override for {c["symbol"]} ({c["key"]})."""')
    call_params: list[str] = []
    for v in views:
        A(f"    {_VIEW_VAR[v]} = {VIEW_BIND[v]}")
        call_params.append(_VIEW_VAR[v])
    for i, (name, bp) in enumerate(args):
        delta = bp - 2       # [bp+N] at hook/callee entry == [sp+N-2]
        A(f"    a{i} = _sx(mem.rw(ss, (sp + {delta}) & 0xFFFF))   # {name}=[bp+{bp}]")
        call_params.append(f"a{i}")
    call = f"_impl({', '.join(call_params)})"
    if c["result"] == "ax":
        A(f"    ax = {call} & 0xFFFF")
        out = "{'ax': ax}"
    elif c["result"] == "dxax":
        A(f"    _r = {call} & 0xFFFFFFFF")
        out = "{'ax': _r & 0xFFFF, 'dx': (_r >> 16) & 0xFFFF}"
    else:                                        # none
        A(f"    {call}")
        out = "{}"
    A(f"    return {out}, {{'flags': 0, 'fmask': 0, 'cost': 1}}")
    A("")
    return "\n".join(L) + "\n"


def contract_of(c: dict) -> dict:
    """The dos_re override contract for a routed entry (fed to
    cpuless_promote --overrides)."""
    views, args = c["views"], c["args"]
    inputs = []
    if views:
        inputs.append("ds")
    if args:
        inputs += ["ss", "sp"]
    result = c["result"]
    outputs = {"ax": ["ax"], "dxax": ["ax", "dx"], "none": []}[result]
    stem = f"func_{c['para_key'].replace(':', '_').lower()}"
    return {
        "name": stem,
        "inputs": sorted(inputs),
        "outputs": outputs,
        "ret_kind": c["ret"],
        "ret_pop": 0,               # adaptgen routes only cdecl (caller-pops);
                                    # ret_cleanup/pascal entries stay literal
        "sp_delta": 0,
        "sp_deltas": [0],
        "needs_plat": False,        # presentation/API subtrees stay literal
        "df_livein": False,
        "flags_livein": False,
        "exit_flags": [],           # a semantic body guarantees no exit flags;
                                    # a caller that reads them stays refused
        "evidence": f"authoritative hand-recovered ({c['impl']}); "
                    f"routed by adaptgen classify (recovered_map.json)",
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ir", default=str(DEFAULT_IR))
    ap.add_argument("--map", default=str(DEFAULT_MAP))
    ap.add_argument("--facts", default=str(DEFAULT_FACTS))
    ap.add_argument("--bodies-dir", default=str(DEFAULT_BODIES),
                    help="where the carrier-free override bodies are written "
                         "(the recovered corpus; must exist -- run AFTER the "
                         "dos_re promoter --apply so they are not wiped)")
    ap.add_argument("--out", default=str(DEFAULT_OUT),
                    help="the override-contract JSON fed to cpuless_promote "
                         "--overrides")
    ap.add_argument("--report", default=str(DEFAULT_REPORT))
    ap.add_argument("--dry-run", action="store_true",
                    help="classify + write overrides.json + report; emit no "
                         "body modules")
    args = ap.parse_args(argv)

    ir_doc = json.loads(Path(args.ir).read_text(encoding="utf-8"))
    map_doc = json.loads(Path(args.map).read_text(encoding="utf-8"))
    facts_doc = adaptgen.load_adapter_facts(Path(args.facts))

    routed, kept = adaptgen.classify(map_doc, ir_doc["functions"], facts_doc)

    overrides = {c["para_key"]: contract_of(c) for c in routed}
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({
        "_notice": "GENERATED by scripts/overridegen.py from recovered_map.json "
                   "+ recovery_ir.json + adapter_facts.json (adaptgen classify). "
                   "Disposable; regenerate, do not hand-edit.",
        "version": 1,
        "overrides": {k: overrides[k] for k in sorted(overrides)},
    }, indent=1), encoding="utf-8")

    written = 0
    if not args.dry_run:
        bodies = Path(args.bodies_dir)
        if not bodies.is_dir():
            raise SystemExit(f"overridegen: bodies dir {bodies} missing -- run "
                             f"the dos_re promoter --apply first")
        for c in routed:
            stem = f"func_{c['para_key'].replace(':', '_').lower()}"
            (bodies / f"{stem}.py").write_text(emit_body(c), encoding="utf-8",
                                               newline="\n")
            written += 1

    reason_counts = Counter()
    for k in kept:
        for r in k["reasons"]:
            reason_counts[r.split("(")[0]] += 1
    report = {
        "version": 1,
        "policy": "unified override-graph (cont.247): carrier-free CPUless "
                  "override bodies for the mechanically-closed contracts "
                  "(adaptgen classify); the rest stay on the GENERATED body.",
        "overrides": sorted(overrides),
        "kept_generated": sorted({k["key"]: k for k in kept}.values(),
                                 key=lambda k: k["key"]),
        "totals": {
            "matched": len(routed) + len(kept),
            "overrides": len(routed),
            "kept_generated": len(kept),
            "kept_by_reason": dict(sorted(reason_counts.items())),
        },
    }
    Path(args.report).parent.mkdir(parents=True, exist_ok=True)
    Path(args.report).write_text(json.dumps(report, indent=1, sort_keys=True)
                                 + "\n", encoding="utf-8")

    print(f"overridegen: {len(routed)}/{len(routed) + len(kept)} matched "
          f"entries composed as CARRIER-FREE CPUless overrides"
          + ("" if args.dry_run else f" ({written} body modules -> "
                                     f"{args.bodies_dir})"))
    print(f"kept on the GENERATED body: {len(kept)} -- by reason:")
    for reason, n in reason_counts.most_common():
        print(f"  {n:4d}  {reason}")
    print(f"overrides contract: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
